#!/usr/bin/env python3

from sys import stdin, stdout, stderr, argv

indent = '  '
attributes = []
model = stdin.read()
class_name = argv[1]
output = 'import \'dart:convert\';\n\nclass %s {\n%sconst %s({\n' % (class_name, indent, class_name)

for line in model.splitlines():
    declaration = line.split(':')
    
    if len(declaration) != 2:
        continue
    
    prop = declaration[0].strip()
    dataType = declaration[1].strip()
    isNullable = dataType.endswith('?')
    
    attributes.append({
        'prop': prop,
        'dataType': dataType,
        'isNullable': isNullable
    })

for attribute in attributes:
    output += '%s%s' % (indent, indent)
    
    if not attribute['isNullable']:
        output += 'required '
    
    output += 'this.%s,\n' % (attribute['prop'],)

output += '%s});\n' % (indent,)

for attribute in attributes:
    output += '\n%sfinal %s %s;' % (indent, attribute['dataType'], attribute['prop'])

output += '\n\n%sfactory %s.fromMap(Map<String, dynamic> map) {' % (indent, class_name,)

output += '\n%s%sreturn %s(' % (indent, indent, class_name)

for attribute in attributes:
    output += '\n%s%s%s%s: map[\'%s\'],' % (indent, indent, indent, attribute['prop'], attribute['prop'])

output += '\n%s%s);' % (indent, indent)

output += '\n%s}' % (indent,)

output += '\n\n%sfactory %s.fromJson(String json) =>\n%s%s%s.fromMap(jsonDecode(json));' % (indent, class_name, indent, indent, class_name)

output += '\n\n%sMap<String, dynamic> toMap() {' % (indent,)

output += '\n%s%sreturn {' % (indent, indent)

for attribute in attributes:
    output += '\n%s%s%s\'%s\': %s,' % (indent, indent, indent, attribute['prop'], attribute['prop'])
    
output += '\n%s%s};' % (indent, indent)

output += '\n%s}' % (indent,)

output += '\n\n%sString toJson() => jsonEncode(toMap());' % (indent,)

stdout.write('%s\n}' % (output,))

